#!/usr/bin/env bash
# information about the school file

for ((i = 1; i <= 100; i++))
do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
	then
		printf "FizzBuzz\n"
	elif [ $((i%5)) -eq 0 ]
	then
		printf "Buzz\n"
	elif [ $((i%3)) -eq 0 ]
	then
		printf "Fizz\n"
	else
		printf "%d\n" $i
	fi
done
