#!/usr/bin/env bash
#time checker

hour=0
minute=1

while [ $hour -le 12 ];
do
	printf "Hour: %d\n" $hour
	
	while [ $minute -le 59 ];
	do
		if [ $minute = 60 ]
		then
			printf "Hour: %d\n" $hour
		else
			printf "%d\n" $minute
			((minute++))
		fi
	done
	((hour++))
	minute=1
done
